export const env = {
  COGNITO_CLIENT_ID: process.env.COGNITO_CLIENT_ID!,
  COGNITO_USER_POOL_ID: process.env.COGNITO_USER_POOL_ID!,
  COGNITO_CLIENT_SECRET: process.env.COGNITO_CLIENT_SECRET!,
  COGNITO_POOL_DOMAIN: process.env.COGNITO_POOL_DOMAIN!,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
}
